# Generated by Django 4.1.2 on 2022-10-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('tel', models.TextField(verbose_name='Tel')),
                ('date', models.DateTimeField(verbose_name='Время')),
                ('hall', models.ImageField(upload_to='', verbose_name='Номер зала')),
            ],
        ),
        migrations.DeleteModel(
            name='ActivationLinks',
        ),
    ]
